### ISSUE TITLE
Proposal: Using vendor to manage packages

### ISSUE THREAD

**Issue by ripcurld0** [MohawkTSDB/mohawk#13]
May I suggest using `vndr` to vendor packages in this project.

For example, to build the command line interface, `mohawk` is using `github.com/spf13/cobra` and `github.com/spf13/viper`. This will require from anyone who builds `mohawk` from source to do `go get -u -v github.com/spf13/viper` before compiling.

This is not always good as at the time of work the master branch was pointing at commit `a` while today master points at commit `b` which breaks the API that was used in commit `a` and that ends in failing to compiling `mohawk` in the future.

**Comment by yaacov** [comment]
a. sound good to me :-)
b. can you make a pull request ( e.g. add the vendor.conf and update the Makefile ) ?
c. does it need changes in the code itself ?

**Comment by ripcurld0** [comment]
Yes, I would like to work on that. It won't take that long.
Also, no change in the code files is required.
