### ISSUE TITLE
How to report a security vulnerability

### ISSUE THREAD

**Issue by BenjaDiaz** [MohawkTSDB/mohawk#173]
I have found a security vulnerability in Mohawk I would like to report. Please provide me with information on how to do so.

Best regards,
Benjamin

**Comment by yaacov** [comment]
:heavy_plus_sign:  @ripcurld (maybe a security issue, adding you to the discussion)

**Comment by ripcurld** [comment]
@BenjaDiaz thanks for noticing this.
@yaacov I guess we should add to `README.md` our emails to send security issues.

**Comment by yaacov** [comment]
Closing.

@BenjaDiaz Thanks :+1:

**Comment by yaacov** [comment]
For any future reader of this issue:

Until we update the readme with new info ... 

a. Best option is to submit a pull request fixing the security issue.
b. Mails are welcome for security issues that you do not want to discuss publicly.

**Comment by yaacov** [comment]
New version 0.33.3:
https://github.com/MohawkTSDB/mohawk/releases/tag/0.33.3
