### ISSUE TITLE
Proposal: Using http.HandlerFunc instead of struct in middleware

### ISSUE THREAD

**Issue by ripcurld0** [MohawkTSDB/mohawk#23]
I would like to suggest a more readable way to create and use middlewares.

Instead of creating a structure with parameters, we can write a function that get those parameters and return a new function that implements the logic of the middleware.

For example, instead of writing a authentication middleware like this

```Go
type AuthMw struct {
  Token string
  RegexpPath string
  next http.Handler
}

func (amw *AuthMw) SetNext(h http.Handler) {
  amw.next = h
}

func (amw *AuthMw) ServeHTTP(w ..., r ...) {
   ...
  amw.next(w, r)
}
```

It will be done in the following way:

```Go
func AuthDecorator(token, regexpPath string) Decorator {
   pRegex := regexp.MustCompile(regexpPath)
   tokenVal := "Bearer " + token
  return Decorator(func(h http.HandlerFunc) http.HandlerFunc {
    ...
    h(w,r)
  })
}
```

In that way we wrote less code and it is easier to reason what the middleware does.

In addition, we could easily wrap middlewares together

```Go
var m Middleware
for ix, mw := range middlewares {
 if ix == 0 {
  m = mw
 } else {
  m = mw(m)
 }
}
```

**Comment by yaacov** [comment]
👍 I talked about it with @nirs and we both think it's a good idea, but it looks like a lot of work, compound by the fact we do no have tests :-)

I will be **very** happy if you can see how much work it is ... the first midlleware that need this is the input part of the gzipper:
https://github.com/MohawkTSDB/mohawk/blob/master/middleware/gizepper.go#L42 

cc @nimrodshn

**Comment by yaacov** [comment]
p.s.
ahh... that need fix too gizepper => gzipper

**Comment by ripcurld0** [comment]
Sure. I have already started writing tests to the middlewares and then refactoring them.
