### ISSUE TITLE
More smoke tests.

### ISSUE THREAD

**Issue by yaacov** [MohawkTSDB/mohawk#51]
Our current smoke tests only check the /status  [1] route in the api module and the --version [2] in the cli module, we need more smoke tests :-)

  - [x] test data post and get
  - [x] alerts on and off
  - [x] alert fire no more then 5 sec after trigger value post,
  - [ ] ~more tests to the cli module~ ( will wait for next iteration :-) )

[1] https://github.com/MohawkTSDB/mohawk/blob/master/test/mohawk.bats#L32
[2] https://github.com/MohawkTSDB/mohawk/blob/master/test/mohawk.bats#L25

**Comment by yaacov** [comment]
cc @ripcurld0 @nimrodshn

**Comment by yaacov** [comment]
@nimrodshn can you take the smoke tests for the alerts ?

**Comment by nimrodshn** [comment]
@yaacov of course

**Comment by yaacov** [comment]
@nimrodshn assigning you to all because:
for testing alerts:
you will have to set the cli + config file, and push values in and get them out,
so this cover all 3 issues in the thread :cat:

**Comment by yaacov** [comment]
@nimrodshn I added a new Item to check the implementation of #60 🎺 

 - [ ] alert fire no more then 5 sec after trigger value post,

**Comment by yaacov** [comment]
and removed the cli tests from the list, too much things for one issue ...

**Comment by yaacov** [comment]
closed by #84
