### ISSUE TITLE
Alert object should hold the time/value value pair at change time

### ISSUE THREAD

**Issue by yaacov** [MohawkTSDB/mohawk#53]
Currently alerts fire, only state that the value is outside valid range, alert object should also hold:
a. time of alert status change
b. time/value pair that triggered the status change.

**Comment by yaacov** [comment]
cc @ripcurld0 @nimrodshn

**Comment by nimrodshn** [comment]
cool! 👍

**Comment by yaacov** [comment]
@nimrodshn do you take this one ?
