### ISSUE TITLE
Fix import packages

### ISSUE THREAD

**Issue by nimrodshn** [MohawkTSDB/mohawk#7]
The import of packages across the project is referencing @yaacov private repo (i.e github.com/yaacov/some_pkg) and it should probably be github.com/MohawkTSDB/mohawk?

Example: (https://github.com/MohawkTSDB/mohawk/blob/421ad737693ad993490f12d57e4bf65a4f13ab0d/backend/memory/memory.go#L25)

**Comment by yaacov** [comment]
👍 can you make a PR ?

**Comment by nimrodshn** [comment]
Ofcourse :)

**Comment by yaacov** [comment]
Fixed by #8
