### ISSUE TITLE
alerts struct to alert buffer should be compatible with prometheus

### ISSUE THREAD

**Issue by yaacov** [MohawkTSDB/mohawk#74]
we currently just dump our alert struct to alert buffer.
prometheus also just dump it's alert struct to alert buffer.

to work with systems the expect prometheus alert struct, we need to dump a struct the looks like a prometheus alert strucs ( this alert mode should have a cli flag like --dump-full-alerts or other flag  )

**Comment by nimrodshn** [comment]
Prometheus alert struct looks like :
```
type Alert struct {
	State AlertState

	Labels      labels.Labels
	Annotations labels.Labels

	// The value at the last evaluation of the alerting expression.
	Value float64
	// The interval during which the condition of this alert held true.
	// ResolvedAt will be 0 to indicate a still active alert.
	ActiveAt   time.Time
	FiredAt    time.Time
	ResolvedAt time.Time
}
```
Everything is clear to me except `Annotations` and `Labels` do you know what is their function? Do we already have implementations for those? just so I know what the gaps are.

**Comment by yaacov** [comment]
> Annotations and Labels do you know what is their function? 

here is an example:

https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb#L48

**Comment by yaacov** [comment]
not targeted to any specific release, closing for now. reopen when target release is set.
